version: '3.9'
services:
  competition-homepage:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - HUGO_VERSION=${HUGO_VERSION}
    container_name: competition-homepage
    image: competition-homepage:latest
    ports:
      - 1314:1314
    command: hugo server --disableFastRender --bind "0.0.0.0" --port 1314
    volumes:
      - ../:/home